name: shared matrix
on:
  workflow_call:

jobs:
  define-matrix:
    runs-on: ubuntu-latest

    outputs:
      os: $
      python: $

    steps:
      - name: Define OS versions
        id: os
        run: |
          echo 'os=[ "windows-latest", "ubuntu-latest", "macos-latest" ]' >> "$GITHUB_OUTPUT"
      - name: Define python versions
        id: python
        run: |
          if [ ${{ github.event_name }} = 'schedule' ]; then
            echo 'python=["3.8", "3.9", "3.10", "3.11", "3.12"]' >> "$GITHUB_OUTPUT"
          else
            echo 'python=["3.8", "3.12"]' >> "$GITHUB_OUTPUT"
          fi
